# Instead of using TAB for indentation, use two spaces at the place of one TAB

# Controller to control robot arm joints
robot_arm_controller:
  type:"position_controllers/JointTrajectoryController"
  joints:[joint_1,joint_2,joint_3,joint_5]

# Controllers to control the end effectors
hand_ee_controller:
  type:"position_controllers/JointTrajectoryController"
  joints:[joint_6,joint_7]

# Controller to continuously publish joint states/positions
joint_state_controller:
  type:"joint_state_controller/JoinStateController"
  publish_rate:50